### ISSUE TITLE
Execute Remote Process and exit without getting Attached to the process

### ISSUE THREAD

**Issue by uday60** [xebialabs/overthere#242]
Thanks for making life easy for other developers by releasing this library.
I am trying to work on a load balancer application where depending upon the load i am executing processes remotely. Since these processes have to run forever if i read from streams my host process is blocked since i am reading from stream. If i exit then the remote process is killed. 

Is there a way to execute the process and exit from the machine ?

**Comment by vpartington** [comment]
The Overthere API does not directly include functionality to start a process in the background. But you can run a script that start a process in the background (with the appropiate `nohup` command). That script will terminate quickly, while leaving that process running.

Alternatively your load balancer application can start a thread to process the streams so that the main thread can continue to do other things. That way you can also terminate the processed started remotely when the load balancer application is terminated.
